DECLARE
    TYPE EmpleadoR IS RECORD (
        NAME VARCHAR2(100),
        SALARIOU EMPLOYEES.SALARY%TYPE,
        CODIGO_DEPT EMPLOYEES.DEPARTMENT_ID%TYPE
    );
    TYPE EmpleadoT IS TABLE OF
        EmpleadoR
    INDEX BY PLS_INTEGER;
    EMPL EmpleadoT;
BEGIN


    FOR I IN 100..206 LOOP
    SELECT FIRST_NAME || ' ' || LAST_NAME, SALARY, DEPARTMENT_ID INTO EMPL(I) FROM EMPLOYEES WHERE EMPLOYEE_ID=I;
    -- DBMS_OUTPUT.PUT_LINE(EMPLE(I));
    END LOOP;
    FOR I IN EMPL.FIRST..EMPL.LAST LOOP
        DBMS_OUTPUT.PUT_LINE(EMPL(I).NAME || ' ' || EMPL(I).SALARIOU || ' ' || EMPL(I).CODIGO_DEPT);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('EL PRIMERO: ' || EMPL(EMPL.FIRST).NAME);
    DBMS_OUTPUT.PUT_LINE('EL ULTIMO: ' || EMPL(EMPL.LAST).NAME);
    DBMS_OUTPUT.PUT_LINE('A BORRAR EMPLEADOS QUE GANEN MENOS DE 7000. ');
    DBMS_OUTPUT.PUT_LINE('ANTES -> ' || EMPL.COUNT);

    FOR I IN EMPL.FIRST..EMPL.LAST LOOP
        IF EMPL(I).SALARIOU < 7000 THEN
            EMPL.DELETE(I);
        END IF;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('DESPUES -> ' || EMPL.COUNT);

END;
