DECLARE
    departamento_id DEPARTMENTS.DEPARTMENT_ID%TYPE;
BEGIN
    SELECT MAX(DEPARTMENT_ID) INTO departamento_id FROM DEPARTMENTS;
    DELETE FROM DEPARTMENTS WHERE DEPARTMENT_ID = departamento_id;
    commit;
END;