DECLARE 
   -- CODIGO DEPARTMENTS.DEPARTMENT_ID%TYPE;
    CURSOR C1(COD DEPARTMENTS.DEPARTMENT_ID%TYPE) IS SELECT COUNT(*) 
    FROM EMPLOYEES WHERE DEPARTMENT_ID = COD;
    NUM_EMPLEADOS NUMBER;
BEGIN
    --CODIGO := 10;
   FOR I IN 1..100 LOOP
    OPEN C1(i);
    FETCH C1 INTO NUM_EMPLEADOS;
        IF NUM_EMPLEADOS > 0 THEN 
         --   DBMS_OUTPUT.PUT_LINE('EL DEPARTAMENTO ' || I || ' NO EXISTE.');
            DBMS_OUTPUT.PUT_LINE('NUMERO DE EMPLEADOS DEl DEPARTAMENTO ' || I || ' ES ' || NUM_EMPLEADOS);
        END IF;
    CLOSE C1;
    END LOOP;
   /* FOR I IN C1 LOOP
        OPEN C1(I.DEPARTMENT_ID);
        DBMS_OUTPUT.PUT_LINE('EN EL DEPARTAMENTO ' || );
    END LOOP;*/
END; 