DECLARE
    CURSOR C1 IS SELECT * FROM EMPLOYEES FOR UPDATE;
BEGIN
    FOR EMPLEADO IN C1 LOOP
        IF EMPLEADO.SALARY > 8000 THEN
            UPDATE EMPLOYEES SET SALARY = SALARY*1.03 WHERE CURRENT OF C1;
        ELSE 
            UPDATE EMPLOYEES SET SALARY = SALARY*1.04 WHERE CURRENT OF C1;
        END IF;
    END LOOP;
    COMMIT;
END;