DECLARE
    empleado_salario EMPLOYEES.SALARY%TYPE;
    CODE VARCHAR2(100);
    MESSAGE VARCHAR2(100);
BEGIN
    SELECT SALARY INTO empleado_salario
    FROM EMPLOYEES WHERE EMPLOYEE_ID = 107; 
    empleado_salario := empleado_salario / 0;
    DBMS_OUTPUT.PUT_LINE('EL SALARIO DEL EMPLEADO QUE BUSCA ES: ' || empleado_salario);
    
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('EL EMPLEADO QUE AH ESTADO BUSCANDO NO EXISTE...');
        WHEN TOO_MANY_ROWS THEN 
        DBMS_OUTPUT.PUT_LINE('SALIERON DEMASIADOS EMPLEADOS JUNTOS, Y SOLO PUEDO CON 1. ');
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('PROBLEMAS EN EL PROGRAMA - GRABES, DANDO EL CODIGO: ' || SQLCODE || ' Y EL MENSAJE ' || SQLERRM);

END;