DECLARE
    DEPARTAMENTO DEPARTMENTS%ROWTYPE;
    jefe DEPARTMENTS.MANAGER_ID%TYPE;
    CURSOR C1 IS SELECT * FROM EMPLOYEES;
    CURSOR C2(j DEPARTMENTS.MANAGER_ID%TYPE) IS SELECT * FROM DEPARTMENTS WHERE MANAGER_ID = j;
BEGIN
    FOR EMPLEADO IN C1 LOOP
        OPEN C2(EMPLEADO.EMPLOYEE_ID);
        FETCH C2 INTO DEPARTAMENTO;
            IF C2%NOTFOUND THEN
                DBMS_OUTPUT.PUT_LINE( EMPLEADO.FIRST_NAME || ' NO ES JEFE DE NADA');
            ELSE 
                DBMS_OUTPUT.PUT_LINE(EMPLEADO.FIRST_NAME || ' ES JEFE DEL DEPARTAMENTO ' || DEPARTAMENTO.DEPARTMENT_NAME);
            END IF;
        CLOSE C2;
    END LOOP;
END;