DECLARE
    empleado_nombre EMPLOYEES.FIRST_NAME%TYPE;
BEGIN
    SELECT FIRST_NAME INTO empleado_nombre
    FROM EMPLOYEES WHERE EMPLOYEE_ID = 50; 
    DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL EMPLEADO QUE BUSCA ES: ' || empleado_nombre);
    
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('EL EMPLEADO QUE AH ESTADO BUSCANDO NO EXISTE...');

        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('PROBLEMAS EN EL PROGRAMA - GRABES...');

END;