DECLARE
    CONTROL_REGIONES EXCEPTION;
    regione_id REGIONS.REGION_ID%TYPE:= 104;
    regione_existe REGIONS.REGION_ID%TYPE;
    regione_name REGIONS.REGION_NAME%TYPE:= 'OCEANIA3';
BEGIN
  --  SELECT REGION_ID INTO regione_existe FROM REGIONS WHERE REGION_ID = regione_id;    
    
    IF regione_id > 200 THEN
       RAISE CONTROL_REGIONES;
    ELSE 
    INSERT INTO REGIONS (REGION_ID, REGION_NAME) VALUES (regione_id, regione_name);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('DATOS INSERTADOS CORRECTAMENTE...');
    END IF;

    EXCEPTION
        WHEN CONTROL_REGIONES THEN 
            DBMS_OUTPUT.PUT_LINE('**REGION NO INSERTADA** --- LA REGION A INSERTAR DEBE SER MENOR A 200');
        WHEN DUP_VAL_ON_INDEX THEN 
            DBMS_OUTPUT.PUT_LINE('**REGION NO INSERTADA** --- LA REGION ' || regione_id || ' A INSERTAR YA EXISTE');
      /*  WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR INDEFINIDO'); */
END;